### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by Rajitha-Gangam** [seqoy/jump#1]
Hi

I cloned project from Github.
I have followed instructions mentioned in below links.

http://seqoy.github.io/jump/Docs/JUMP/html/installing.html
http://seqoy.github.io/jump/Docs/JUMP/html/importing_project.html
https://github.com/seqoy/jump

I am using below code for create instance of JPPipeline.
JPPipeline *obj=[JPPipeline init];

But I am getting the below error, When I want use the JPPipeline instance.
If I comment above line everything working fine.

Undefined symbols for architecture i386:
  "_JPLogIfYouCan", referenced from:
      -[JPPipeline notifyHandlerException:withEvent:] in libJUMPNetwork.a(JPPipeline.o)
      -[JPPipeline sendUpstream:] in libJUMPNetwork.a(JPPipeline.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please anyone help me to resolve this issue.
It as major priority of my task. I have strucked at this point since 1 month.

Thanks

**Comment by seqoy** [comment]
Hi Rajitha, you should try https://github.com/seqoy/jump2 - Is the same project restarted and simplified. Using Cocoapods.

**Comment by Rajitha-Gangam** [comment]
I resolved issue.
